#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""DigitalPilot · 通用 LUT Verilog 生成器(零依赖,py3.6 兼容)。

把任意一元函数打表成 Verilog function 的 case 语句,逐项 = round(f(idx)·scale),
并自带自检(重算一遍逐项比对)。典型用法——四分之一波 cos 表(1025 项,Q12):

  ./gen_lut.py --name quarter_cos_q12 --n 1025 --width-in 11 --width-out 14 \\
      --signed --expr "math.cos(math.pi/2 * i / 1024)" --scale 4096 > lut.v

参数:
  --expr   对 i(0..n-1)求值的 python 表达式,可用 math.*
  --scale  定点放大倍数(round 到整数)
  --signed 输出声明为 signed
"""
import argparse
import math  # noqa: F401  (供 --expr 使用)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--n", type=int, required=True, help="表项数(idx 0..n-1)")
    ap.add_argument("--width-in", type=int, required=True)
    ap.add_argument("--width-out", type=int, required=True)
    ap.add_argument("--expr", required=True)
    ap.add_argument("--scale", type=float, default=1.0)
    ap.add_argument("--signed", action="store_true")
    a = ap.parse_args()

    vals = []
    for i in range(a.n):
        v = eval(a.expr, {"math": math, "i": i})  # noqa: S307 受控输入
        x = v * a.scale
        r = int(math.floor(x + 0.5)) if x >= 0 else -int(math.floor(-x + 0.5))
        lim = 1 << (a.width_out - 1 if a.signed else a.width_out)
        if not (-lim <= r < lim if a.signed else 0 <= r < lim):
            raise SystemExit("idx=%d 值 %d 超出 %d bit 范围" % (i, r, a.width_out))
        vals.append(r)

    sgn = "signed " if a.signed else ""
    lit = lambda r: "%d'sd%d" % (a.width_out, r) if a.signed and r >= 0 else (
        "-%d'sd%d" % (a.width_out, -r) if a.signed else "%d'd%d" % (a.width_out, r))
    print("// generated by DigitalPilot gen_lut.py: n=%d scale=%g expr=%s"
          % (a.n, a.scale, a.expr))
    print("function %s[%d:0] %s;" % (sgn, a.width_out - 1, a.name))
    print("    input [%d:0] idx;" % (a.width_in - 1))
    print("    begin\n        case (idx)")
    for i, r in enumerate(vals):
        print("        %d'd%d: %s = %s;" % (a.width_in, i, a.name, lit(r)))
    print("        default: %s = %s;" % (a.name, lit(0)))
    print("        endcase\n    end\nendfunction")

    # 自检:重算逐项比对(防 eval/舍入实现回归)
    for i in range(a.n):
        v = eval(a.expr, {"math": math, "i": i}) * a.scale
        r = int(math.floor(v + 0.5)) if v >= 0 else -int(math.floor(-v + 0.5))
        assert r == vals[i], "self-check fail @%d" % i


if __name__ == "__main__":
    main()
