# DigitalPilot · dont_use 清单(最终可行版;调整原则见 dont_use_note.md)
echo "SOC_MESSAGE: precision dont_use - modern get_lib_cells syntax"
set_dont_use [get_lib_cells ${library_name}/CLK*]
set_dont_use [get_lib_cells ${library_name}/DFFHQXL]
set_dont_use [get_lib_cells ${library_name}/DFFSHQXL]
set_dont_use [get_lib_cells ${library_name}/DFFSRHQXL]
set_dont_use [get_lib_cells ${library_name}/DFFTRXL]
set_dont_use [get_lib_cells ${library_name}/DFFXL]
set_dont_use [get_lib_cells ${library_name}/DFFSXL]
set_dont_use [get_lib_cells ${library_name}/DFFRXL]
set_dont_use [get_lib_cells ${library_name}/TBUF*]
set_dont_use [get_lib_cells ${library_name}/*X20]
set_dont_use [get_lib_cells ${library_name}/*X16]
set_dont_use [get_lib_cells ${library_name}/*X12]
set_dont_use [get_lib_cells ${library_name}/AFC*]
set_dont_use [get_lib_cells ${library_name}/AFH*]
set_dont_use [get_lib_cells ${library_name}/AHH*]
set_dont_use [get_lib_cells ${library_name}/BENC*]
set_dont_use [get_lib_cells ${library_name}/BMX*]
set_dont_use [get_lib_cells ${library_name}/RF*]
set_dont_use [get_lib_cells ${library_name}/CMPR*]
set_dont_use [get_lib_cells ${library_name}/TLAT*]
set_dont_use [get_lib_cells ${library_name}/SDFF*]
set_dont_use [get_lib_cells ${library_name}/SEDFF*]
set_dont_use [get_lib_cells ${library_name}/JK*]
set_dont_use [get_lib_cells ${library_name}/EDFF*]
